from .antiakamai_bmp import AntiAkamaiBMPTask
from .antikasada import AntiKasadaTask
from .datadome_slider import DataDomeSliderTask
from .recaptcha_v2 import RecaptchaV2Task
from .recaptcha_v2_enterprise import RecaptchaV2EnterpriseTask
from .fun_captcha import FunCaptchaTask
from .funcaptcha_classification import FunCaptchaClassificationTask
from .hcaptcha_classification import HCaptchaClassificationTask
from .image_to_text import ImageToTextTask
from .gee_test import GeeTestTask
from .h_captcha import HCaptchaTask
from .recaptcha_v3 import RecaptchaV3Task
from .utils import CapSolverException